name: Application 007 
on: push
  


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install Libraries
        run: pip install flake8
      - name: lint with Flake8
        run: |
            cd function
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=0 --max-line-length=127 --statistics
             
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -r requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Zip Bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name:  Zipped-bundle 
          path: ${{ github.sha }}.zip
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: create release 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release from ${{ github.run_number }}
          body: New release for ${{ github.sha }}. Release notes
          draft: false
          prerelease: false 
  documentation:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create page directory
        run: mkdir docs
      - name: convert markdown to html
        uses: docker://pandoc/core:2.9
        with:
          args: userguide.md -t html -o docs/index.html
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with: 
          branch: gh-pages
          folder: docs
      
          
            
 
